enum SECTION {
  DASHBOARD,
  BUSINESS,
  MODULES,
  TEMPLATE
}

//--- MODULE ---

enum NAVIGATOR_MODULE_MAIN {
  PAGE_MAIN_LIST_MODULES, //default
  PAGE_EDIT_MODULE,
  PAGE_NEW_MODULE
}

//--- BUSINESS ---

enum NAVIGATOR_BUSINESS_MAIN {
  PAGE_MAIN_LIST_BUSINESS, //default
  PAGE_DETAIL_BUSINESS
}

enum NAVIGATOR_BUSINESS_MODULE {
  PAGE_MAIN_LIST_BUSINESS, //default
  PAGE_LIST_BUSINESS_MODULES,
  PAGE_LIST_MODULES,
  PAGE_EDIT_MODULE
}